/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedLayoutRouteImport } from './routes/_authed-layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout'
import { Route as AuthedLayoutIndexRouteImport } from './routes/_authed-layout/index'
import { Route as AuthedLayoutSettingsRouteImport } from './routes/_authed-layout/settings'
import { Route as AuthLayoutSignInRouteImport } from './routes/_auth-layout/sign-in'
import { Route as AuthLayoutAuthenticationErrorRouteImport } from './routes/_auth-layout/authentication-error'
import { Route as AuthedLayoutChatsIdRouteImport } from './routes/_authed-layout/chats/$id'

const AuthedLayoutRoute = AuthedLayoutRouteImport.update({
  id: '/_authed-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutIndexRoute = AuthedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedLayoutRoute,
} as any)
const AuthedLayoutSettingsRoute = AuthedLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedLayoutRoute,
} as any)
const AuthLayoutSignInRoute = AuthLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthenticationErrorRoute =
  AuthLayoutAuthenticationErrorRouteImport.update({
    id: '/authentication-error',
    path: '/authentication-error',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthedLayoutChatsIdRoute = AuthedLayoutChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AuthedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedLayoutIndexRoute
  '/authentication-error': typeof AuthLayoutAuthenticationErrorRoute
  '/sign-in': typeof AuthLayoutSignInRoute
  '/settings': typeof AuthedLayoutSettingsRoute
  '/chats/$id': typeof AuthedLayoutChatsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedLayoutIndexRoute
  '/authentication-error': typeof AuthLayoutAuthenticationErrorRoute
  '/sign-in': typeof AuthLayoutSignInRoute
  '/settings': typeof AuthedLayoutSettingsRoute
  '/chats/$id': typeof AuthedLayoutChatsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/_authed-layout': typeof AuthedLayoutRouteWithChildren
  '/_auth-layout/authentication-error': typeof AuthLayoutAuthenticationErrorRoute
  '/_auth-layout/sign-in': typeof AuthLayoutSignInRoute
  '/_authed-layout/settings': typeof AuthedLayoutSettingsRoute
  '/_authed-layout/': typeof AuthedLayoutIndexRoute
  '/_authed-layout/chats/$id': typeof AuthedLayoutChatsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication-error'
    | '/sign-in'
    | '/settings'
    | '/chats/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authentication-error' | '/sign-in' | '/settings' | '/chats/$id'
  id:
    | '__root__'
    | '/_auth-layout'
    | '/_authed-layout'
    | '/_auth-layout/authentication-error'
    | '/_auth-layout/sign-in'
    | '/_authed-layout/settings'
    | '/_authed-layout/'
    | '/_authed-layout/chats/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AuthedLayoutRoute: typeof AuthedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed-layout': {
      id: '/_authed-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed-layout/': {
      id: '/_authed-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutIndexRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/_authed-layout/settings': {
      id: '/_authed-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedLayoutSettingsRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/_auth-layout/sign-in': {
      id: '/_auth-layout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthLayoutSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/authentication-error': {
      id: '/_auth-layout/authentication-error'
      path: '/authentication-error'
      fullPath: '/authentication-error'
      preLoaderRoute: typeof AuthLayoutAuthenticationErrorRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authed-layout/chats/$id': {
      id: '/_authed-layout/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AuthedLayoutChatsIdRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutAuthenticationErrorRoute: typeof AuthLayoutAuthenticationErrorRoute
  AuthLayoutSignInRoute: typeof AuthLayoutSignInRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuthenticationErrorRoute: AuthLayoutAuthenticationErrorRoute,
  AuthLayoutSignInRoute: AuthLayoutSignInRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AuthedLayoutRouteChildren {
  AuthedLayoutSettingsRoute: typeof AuthedLayoutSettingsRoute
  AuthedLayoutIndexRoute: typeof AuthedLayoutIndexRoute
  AuthedLayoutChatsIdRoute: typeof AuthedLayoutChatsIdRoute
}

const AuthedLayoutRouteChildren: AuthedLayoutRouteChildren = {
  AuthedLayoutSettingsRoute: AuthedLayoutSettingsRoute,
  AuthedLayoutIndexRoute: AuthedLayoutIndexRoute,
  AuthedLayoutChatsIdRoute: AuthedLayoutChatsIdRoute,
}

const AuthedLayoutRouteWithChildren = AuthedLayoutRoute._addFileChildren(
  AuthedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AuthedLayoutRoute: AuthedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
